# Generated by Django 5.0.1 on 2024-02-07 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Optical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Outside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpareCarYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('year', models.DateField(help_text='Masalan, 1998 yoki 2007')),
                ('price', models.IntegerField()),
                ('is_less', models.CharField(choices=[('Ha', 'Yes'), ("Yo'q", 'No')], default="Yo'q", max_length=32)),
                ('fuel_type', models.CharField(choices=[('Benzin', 'Petrol'), ('Gaz benzin', 'Gaz Gasoline'), ('Dizel', 'Diesel'), ('Elektr', 'Electric'), ('Gibrid', 'Hybrid'), ('Gaz', 'Gas')], default='Benzin', max_length=64)),
                ('transmission', models.CharField(choices=[('Mexanika', 'Mechanic'), ('Avtomat', 'Automatic'), ('Tiptronik', 'Tiptronics'), ('Variator', 'Diammer'), ('Robot', 'Robot')], max_length=128)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('volume', models.FloatField(blank=True, help_text='Masalan, 2.8 yoki 3', null=True)),
                ('walking', models.FloatField(blank=True, null=True)),
                ('color_status', models.CharField(blank=True, choices=[('Kraska toza', 'Clear'), ('Kraskasi bor', 'Has'), ('Petno bor', 'Pyatno'), ("To'liq kraska", 'Full')], max_length=128, null=True)),
                ('extension', models.CharField(blank=True, choices=[('Oldi', 'Before'), ('Orqa', 'Back'), ("To'liq", 'Full')], max_length=64, null=True)),
                ('additional', models.CharField(blank=True, choices=[("Texnik ko'rikdan o'tgan", 'Tested'), ("Pul sarflashning hojati yo'q", 'Spend Money')], max_length=256, null=True)),
                ('information', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, help_text='Copy the file here.', null=True, upload_to='cars/')),
                ('body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.carbody')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.color')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.district')),
                ('media', models.ManyToManyField(blank=True, null=True, to='blog.media')),
                ('optical', models.ManyToManyField(blank=True, null=True, to='blog.optical')),
                ('outside', models.ManyToManyField(blank=True, null=True, to='blog.outside')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.region')),
                ('salon', models.ManyToManyField(blank=True, null=True, to='blog.salon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Copy the file here.', null=True, upload_to='spare/')),
                ('information', models.TextField(blank=True, null=True)),
                ('condition_spare', models.CharField(choices=[('Yangi', 'New'), ('Islatilgan', 'Used')], max_length=128)),
                ('is_less', models.CharField(choices=[('Ha', 'Yes'), ("Yo'q", 'No')], default="Yo'q", max_length=64)),
                ('delivery', models.CharField(choices=[('Ha', 'Yes'), ("Yo'q", 'No')], max_length=128)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.carmodel')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.region')),
                ('car_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.sparecaryear')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.typecars')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='carmodel',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.typecars'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='vehicle_option',
            field=models.ManyToManyField(blank=True, null=True, to='blog.vehicleoption'),
        ),
    ]
